import './globals.css'

import type { Metadata } from 'next'
import { FC, PropsWithChildren } from 'react'

import ogImage from '../../public/og.jpg'

export const metadata: Metadata = {
	title: 'FIMI Lucky',
	description: 'Generated by create next app',
	openGraph: {
		title: 'Đăng ký mã giới thiệu',
		description: 'FIMI - Giải pháp bán hàng đa kênh',
		url: 'https://fimi-register.vercel.app',
		siteName: 'FIMI',
		images: [
			{
				url: ogImage.src,
				width: ogImage.width,
				height: ogImage.height
			}
		]
	}
}

const RootLayout: FC<PropsWithChildren> = ({ children }) => {
	return (
		<html lang='en'>
			<body className={` antialiased`}>{children}</body>
		</html>
	)
}

export default RootLayout
